### ISSUE TITLE
Changed location of sources.list within Debian image breaks building custom Docker srb2bld image.

### ISSUE THREAD

**Issue by LegoLuigiJumpscare** [Bijman/srb2bld#24]
proof:

https://github.com/Bijman/srb2bld/assets/146545399/83f7833b-1cfb-49a5-bfc6-ed95b6401594

**Comment by Bijman** [comment]
There was a change in location of file `sources.list` within Debian container, which causes this issue.

**Comment by Bijman** [comment]
Updated srb2bld with commit c3fad9c44, that should solve the issue.

**Comment by LegoLuigiJumpscare** [comment]
https://github.com/Bijman/srb2bld/assets/146545399/56568f7a-bfad-4fb4-8474-2445fb59976a

its not fixed (somehow)

**Comment by Bijman** [comment]
Moved to #25.
